### PR TITLE
Make source able to compile on Qt>=5.15.0

### LINKED ISSUE #1616: Build fails on Qt5 5.15.0
Build fails due to newer QNetworkReply API.

**To Reproduce**
Build with Qt5 5.15.0

**Logs**
<pre><code>/usr/include/qt/QtNetwork/qnetworkreply.h:161:10: note: declared here
  161 |     void error(QNetworkReply::NetworkError);
      |          ^~~~~
/home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp: In member function ‘void multipass::LocalSocketReply::parse_status(const QByteArray&)’:
/home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp:231:50: error: ‘void QNetworkReply::error(QNetworkReply::NetworkError)’ is deprecated: Use QNetworkReply::errorOccurred(QNetworkReply::NetworkError) instead [-Werror=deprecated-declarations]
  231 |         emit error(QNetworkReply::ProtocolFailure);
      |                                                  ^
In file included from /usr/include/qt/QtNetwork/QNetworkReply:1,
                 from /home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.h:23,
                 from /home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp:18:
/usr/include/qt/QtNetwork/qnetworkreply.h:161:10: note: declared here
  161 |     void error(QNetworkReply::NetworkError);
      |          ^~~~~
/home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp:245:30: error: ‘void QNetworkReply::error(QNetworkReply::NetworkError)’ is deprecated: Use QNetworkReply::errorOccurred(QNetworkReply::NetworkError) instead [-Werror=deprecated-declarations]
  245 |         emit error(error_code);
      |                              ^
In file included from /usr/include/qt/QtNetwork/QNetworkReply:1,
                 from /home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.h:23,
                 from /home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp:18:
/usr/include/qt/QtNetwork/qnetworkreply.h:161:10: note: declared here
  161 |     void error(QNetworkReply::NetworkError);
      |          ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/network/CMakeFiles/network.dir/build.make:96: src/network/CMakeFiles/network.dir/local_socket_reply.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5111: src/network/CMakeFiles/network.dir/all] Error 2
make: *** [Makefile:161: all] Error 2</code></pre>

**Additional info**
 - OS: Arch Linux 5.4.48
- cmake version: 3.17.3

### PR DESCRIPTION
**Pull request by ragouel**
Closes #1616 relates to #1617

### CODE REVIEW

**Comment by ragouel** [comment]
``query_in_url_is_preserved`` test is failing but it seems unrelated to my changes, since I've included #ifdefs for backwards compatibility this time.

**Comment by Saviq** [comment]
Hi @ragouel, thanks for this!

There's a test failure, however:
```

[ RUN      ] LocalNetworkAccessManager.query_in_url_is_preserved
/root/parts/multipass/src/tests/linux/test_local_network_access_manager.cpp:282: Failure
Value of: data.contains(query_string.toLatin1())
  Actual: false
Expected: true
[  FAILED  ] LocalNetworkAccessManager.query_in_url_is_preserved (1 ms)
```

The test itself is here:

https://github.com/canonical/multipass/blob/d9d02f16c231d46c089d7079ac3f86fab1088d82/tests/linux/test_local_network_access_manager.cpp#L271-L289

And the relevant piece of code:
https://github.com/canonical/multipass/blob/d9d02f16c231d46c089d7079ac3f86fab1088d82/src/network/local_socket_reply.cpp#L148-L151

Not sure why this would happen, just yet. Let us know please if you dig something out.

**Comment by Saviq** [comment]
> Not sure why this would happen, just yet. Let us know please if you dig something out.

Hi @ragouel, I cleaned this up a bit, if it works for you still, this would be good to go :)

bors try

**Comment by Saviq** [comment]
OK, so `QString::` has to stay for older Qts.

**Comment by Saviq** [comment]
bors try

**Comment by ragouel** [comment]
Hello @Saviq, it's compiling now. Thank you for fixing it.

**Comment by Saviq** [comment]
Hi @ragouel, Just confirming all is fine on 5.15 and I'll clean this branch up a bit and get it in, thanks again for your contribution! :)

**Comment by Saviq** [comment]
bors try

**Review by Saviq — APPROVED** [review]
Alright, then, this looks good!

bors r+
