### ISSUE TITLE
Symbol not found trying to run on OSX 10.11.6

### ISSUE THREAD

**Issue by iammer** [canonical/multipass#1258]
Just installed 1.0.0 on OSX 10.11.6.  When I try to run I get the following error:

```
$ multipass
dyld: Symbol not found: __ZNSt19bad_optional_accessD1Ev
  Referenced from: /usr/local/bin/multipass
  Expected in: /usr/lib/libc++.1.dylib
 in /usr/local/bin/multipass
Trace/BPT trap: 5
```

**Comment by Saviq** [comment]
Hi @iammer, it looks like we're using features from libraries of newer macOS than you're on… Any chance you could upgrade to the latest?

**Comment by iammer** [comment]
Yes.
You might want to update your downloads page, it lists the minimum macOS version as: Yosemite 10.10.3 or later.

**Comment by Saviq** [comment]
Hi @iammer, yes, we'll need to check what's the earliest we can run on - we didn't know about this new limitation. We may also try and work around the issue.

**Comment by fclaerho** [comment]
Confirming I have the exact same issue, El Capitan (10.11.6).

**Comment by robbles** [comment]
Same issue on Sierra (10.12.6).

**Comment by townsend2010** [comment]
For reference: https://stackoverflow.com/questions/58469837/how-do-i-include-a-particular-version-of-the-c-library-in-a-mac-os-bundle-made

**Comment by townsend2010** [comment]
Could someone affected by this please post the output of `nm -gU /usr/lib/libc++.1.dylib | grep optional`?

Thanks!

**Comment by townsend2010** [comment]
I *think* I may have found the root cause of this.  Could anyone affected by this please try a [test Multipass package](https://transfer.sh/PatQj/multipass-1.1.0-dev.594+gbbfa89bd.mac-Darwin.pkg)?

Thanks!

**Comment by townsend2010** [comment]
Hey all,

It looks like `transfer.sh` is having problems, so please try the package found at https://easyupload.io/noxhg8.

Thanks!

**Comment by beilmit** [comment]
Hi @townsend2010 
I tested the operation using the specified test package on my environment. The results are as follows.

```
* 10.11
kurosawa-no-Mac:~ kurosawa$ multipass version
Sorry, "multipass" cannot be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.

kurosawa-no-Mac:~ kurosawa$ /Library/Application\ Support/com.canonical.multipass/bin/multipassd -v
dyld: Symbol not found: __ZNSt19bad_optional_accessD1Ev
  Referenced from: /Library/Application Support/com.canonical.multipass/bin/multipassd
  Expected in: /usr/lib/libc++.1.dylib
 in /Library/Application Support/com.canonical.multipass/bin/multipassd
Trace/BPT trap: 5

kurosawa-no-Mac:~ kurosawa$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G22010


* 10.12
kurosawanoMac:~ kurosawa$ multipass version
multipass  1.1.0-dev.595+g0b20fc69.mac

kurosawanoMac:~ kurosawa$ /Library/Application\ Support/com.canonical.multipass/bin/multipassd -v
dyld: Symbol not found: __ZNSt19bad_optional_accessD1Ev
  Referenced from: /Library/Application Support/com.canonical.multipass/bin/multipassd
  Expected in: /usr/lib/libc++.1.dylib
 in /Library/Application Support/com.canonical.multipass/bin/multipassd
Abort trap: 6

kurosawanoMac:~ kurosawa$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G2136


* 10.13
kurosawanomakku:~ kurosawa$ multipass version
multipass  1.1.0-dev.595+g0b20fc69.mac
multipassd 1.1.0-dev.595+g0b20fc69.mac

kurosawanomakku:~ kurosawa$ /Library/Application\ Support/com.canonical.multipass/bin/multipassd -v
multipassd 1.1.0-dev.595+g0b20fc69.mac

kurosawanomakku:~ kurosawa$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G66
```

**Comment by townsend2010** [comment]
@beilmit,

Thanks so much for testing this!  Too bad it didn't fix the issue.  I'm going to have to try something else to help me reproduce this so I can properly debug and try to find a fix.

One interesting thing I see in your output though is that the version of Qt we are using requires OSX 10.12 or later, so we will need to update our minimum OSX version we support.

**Comment by townsend2010** [comment]
After doing more research on this issue, it seems the recommended option is to build using the oldest OSX version we support.  See https://stackoverflow.com/questions/15091105/confusion-of-how-to-make-osx-app-backward-compatible-how-to-test-them for more info.

We currently build on 10.13, so we need to decide if 10.13 is the minimum version we support or build on 10.12 (or earlier) (if we can).

@Saviq, any thoughts?

**Comment by lowemasterpro** [comment]
I'm (currently) running Sierra (10.12.6) and was able to install and run the multipass client from your test package which got me around the original missing symbol issue mentioned by the OP. However, it looks like `multipassd` has the same issue. Any command issued to `multipass` results in the error:

```
lowey@Serenity:~$ multipass start
start failed: cannot connect to the multipass socket                            
Please ensure multipassd is running and '/var/run/multipass_socket' is accessible
```

Executing `multipassd` directly I run into our old friend once again:

```
lowey@Serenity:~$ /Library/Application\ Support/com.canonical.multipass/bin/multipassd 
dyld: Symbol not found: __ZNSt19bad_optional_accessD1Ev
  Referenced from: /Library/Application Support/com.canonical.multipass/bin/multipassd
  Expected in: /usr/lib/libc++.1.dylib
 in /Library/Application Support/com.canonical.multipass/bin/multipassd
Abort trap: 6
```

So whatever your fix for the client was needs applying to the server. Although I do intend on upgrading OSX ASAP as multipass isn't the only app I'm having this issue with.

https://github.com/canonical/multipass/issues/1258#issuecomment-578266507

> Could someone affected by this please post the output of nm -gU /usr/lib/libc++.1.dylib | grep optional?

Just in case it's of any use, on my system it returned nothing:

```
lowey@Serenity:~$ nm -gU /usr/lib/libc++.1.dylib | grep optional
lowey@Serenity:~$ 
```

**Comment by matthewpaulthomas** [comment]
[multipass.run#75](https://github.com/canonical-web-and-design/multipass.run/issues/75) shows Multipass claiming to require not 10.12 or 10.13, but 10.14:

![image](https://user-images.githubusercontent.com/15259299/74588063-9355f300-500a-11ea-8550-90d0f2752114.png)

The sooner you decide on a minimum, the sooner we can fix the front page of the site.

In case it helps, [netmarketshare.com stats from January](https://netmarketshare.com/operating-system-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22platform%22%3A%7B%22%24in%22%3A%5B%22Mac%20OS%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22platformVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22platformsDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222019-02%22%2C%22dateEnd%22%3A%222020-01%22%2C%22segments%22%3A%22-1000%22%7D):

macOS version | Using that version or later
-|-
10.15 | 10.06%
10.14 | 60.91%
10.13 | 79.73%
10.12 | 88.30%
10.11 | 94.36%

**Comment by townsend2010** [comment]
What is prompting the `10.14` requirement here?  We build on a `10.13` environment, so until we can find a solution to work on older OSX versions, I'm keen on making the minimum version `10.13`.  However, it troubles me that a user got that popup indicating `10.14` is the minimum from the `multipass-gui` app.

**Comment by Saviq** [comment]
Hi all, we've looked around a lot and decided to settle on **macOS 10.12 Sierra** as our lowest supported macOS version. Going lower than that would mean we're going out of support for some of our dependencies.

Even the oldest hardware that can still run Multipass is supported through 10.13 High Sierra, so we should not be cutting anyone off.

Anyone with 10.12 or 10.13 if you could please test the package uploaded here:
https://github.com/canonical/multipass/pull/1392#issuecomment-592463656

On 10.11, the installer should fail early.

**Comment by Saviq** [comment]
@talyguryn, could you try the above, too, assuming you're on 10.13 still? Thanks!

**Comment by lowemasterpro** [comment]
@Saviq Tested on 10.12.6 and appears to be working well so far. Thanks!

**Comment by nana-marinbio** [comment]
> Hi all, we've looked around a lot and decided to settle on **macOS 10.12 Sierra** as our lowest supported macOS version. Going lower than that would mean we're going out of support for some of our dependencies.
> 
> Even the oldest hardware that can still run Multipass is supported through 10.13 High Sierra, so we should not be cutting anyone off.
> 
> Anyone with 10.12 or 10.13 if you could please test the package uploaded here: [#1392 (comment)](https://github.com/canonical/multipass/pull/1392#issuecomment-592463656)
> 
> On 10.11, the installer should fail early.

Hi @Saviq 
I am running macOS 10.12 and trying to use the package loaded in #1392 but the link is not working. Is it still available somewhere??
tks

**Comment by Saviq** [comment]
Sorry @nana-marinbio, the latest Multipass won't support 10.12 any more. 10.14 is currently the minimal supported version (although 10.15 will be a requirement soon, 10.14 does not receive Apple support since October).

You can try one of the old releases (https://github.com/canonical/multipass/releases) - try 1.2.0 or 1.3.0. But it's discouraged, and you won't get updates or any new features.

**Comment by nana-marinbio** [comment]
Hi @Saviq,
I had already installed version 1.1 when you replied.
It was working fine for the job I need.
I transfered files from host to it, but now I cannot transfer files from instance to host, even the same files.
Example:
AnaPaula$ <multipass transfer /Users/AnaPaula/Downloads/muscle5.1.linux_intel64 ubuntu18:> (worked fine)

AnaPaula$ <multipass transfer ubuntu18:/muscle5.1.linux_intel64 /Users/AnaPaula/Desktop>
transfer failed: [sftp pull] open failed: 'SFTP server: No such file'

AnaPaula$ <multipass transfer ubuntu18:/muscle5.1.linux_intel64 /Users/AnaPaula/Desktop/muscle5.1.linux_intel64>
transfer failed: [sftp pull] open failed: 'SFTP server: No such file'

Except for this, I did most of my job using v1.1. Now I need to transfer files to host!
Is there anything I can try?
Tks

**Comment by Saviq** [comment]
@nana-marinbio does the file exist? `multipass exec ubuntu18 -- ls /`

**Comment by nana-marinbio** [comment]
@Saviq 

AnaPaula$ <multipass exec ubuntu18 -- ls />
Users  bin  boot  dev  etc  home  initrd.img  initrd.img.old  lib  lib64  lost+found  media  mnt  opt  proc  root  run	sbin  snap  srv  sys  tmp  usr	var  vmlinuz  vmlinuz.old

ubuntu@ubuntu18:~$ <ls>
BLCA  muscle  muscle5.1.linux_intel64  ncbi-blast+

**Comment by nana-marinbio** [comment]
Michael,
Is it possible to increase the 4.67GB  for usage?
I did not find any issue or documentation on this.
tks in advance



>(((·>  ~~ >(((·> ~~ >(((·>
Ana Paula B. Moreira, PhD
Federal University of Rio de Janeiro- UFRJ
Biology Institute
Phone: +55 21 988220753
ID Orcid <https://orcid.org/0000-0001-9757-1317>
ResearchGate <https://www.researchgate.net/profile/Ana_Paula_Moreira4>
Loop <https://loop.frontiersin.org/people/242799/overview>
Twitter @AnaPaula_BM <https://twitter.com/AnaPaula_BM>
FB @somostodosciencia <https://www.facebook.com/somostodosciencia>


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
04/07/22,
04:49:47 PM

**Comment by nana-marinbio** [comment]
Just found the issue under resize, trying to figure out what might apply to
me... and if I can make it



>(((·>  ~~ >(((·> ~~ >(((·>
Ana Paula B. Moreira, PhD
Federal University of Rio de Janeiro- UFRJ
Biology Institute
Phone: +55 21 988220753
ID Orcid <https://orcid.org/0000-0001-9757-1317>
ResearchGate <https://www.researchgate.net/profile/Ana_Paula_Moreira4>
Loop <https://loop.frontiersin.org/people/242799/overview>
Twitter @AnaPaula_BM <https://twitter.com/AnaPaula_BM>
FB @somostodosciencia <https://www.facebook.com/somostodosciencia>
