### ISSUE TITLE
Build fails on Qt5 5.15.0

### ISSUE THREAD

**Issue by dkiziridis** [canonical/multipass#1616]
Build fails due to newer QNetworkReply API.

**To Reproduce**
Build with Qt5 5.15.0

**Logs**
<pre><code>/usr/include/qt/QtNetwork/qnetworkreply.h:161:10: note: declared here
  161 |     void error(QNetworkReply::NetworkError);
      |          ^~~~~
/home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp: In member function ‘void multipass::LocalSocketReply::parse_status(const QByteArray&)’:
/home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp:231:50: error: ‘void QNetworkReply::error(QNetworkReply::NetworkError)’ is deprecated: Use QNetworkReply::errorOccurred(QNetworkReply::NetworkError) instead [-Werror=deprecated-declarations]
  231 |         emit error(QNetworkReply::ProtocolFailure);
      |                                                  ^
In file included from /usr/include/qt/QtNetwork/QNetworkReply:1,
                 from /home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.h:23,
                 from /home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp:18:
/usr/include/qt/QtNetwork/qnetworkreply.h:161:10: note: declared here
  161 |     void error(QNetworkReply::NetworkError);
      |          ^~~~~
/home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp:245:30: error: ‘void QNetworkReply::error(QNetworkReply::NetworkError)’ is deprecated: Use QNetworkReply::errorOccurred(QNetworkReply::NetworkError) instead [-Werror=deprecated-declarations]
  245 |         emit error(error_code);
      |                              ^
In file included from /usr/include/qt/QtNetwork/QNetworkReply:1,
                 from /home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.h:23,
                 from /home/crow/Git/BROKEN/canonical-multipass-git/src/canonical-multipass/src/network/local_socket_reply.cpp:18:
/usr/include/qt/QtNetwork/qnetworkreply.h:161:10: note: declared here
  161 |     void error(QNetworkReply::NetworkError);
      |          ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/network/CMakeFiles/network.dir/build.make:96: src/network/CMakeFiles/network.dir/local_socket_reply.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5111: src/network/CMakeFiles/network.dir/all] Error 2
make: *** [Makefile:161: all] Error 2</code></pre>

**Additional info**
 - OS: Arch Linux 5.4.48
- cmake version: 3.17.3
