### ISSUE TITLE
Can't build on Questing with Clang 20 and Mold

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#4664]
**Describe the bug**
Attempting to build on Ubuntu 25.10 (Questing Quokka), with Clang 20 and Mold, fails for various reasons.

1. Syntax error in our code:
```
error: identifier '_semver' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
```
2. Compilation error in `fmt`:
```
error: call to consteval function 'fmt::basic_format_string<char, fmt::basic_string_view<char> &, const char(&)[3]>::basic_format_string <FMT_COMPILE_STRING, 0>' is not a constant expression
```
3. Undefined `absl` symbol when linking:
```
mold: error: undefined symbol: _ZN4absl12lts_2025012712log_internal10LogMessagelsImTnNSt9enable_ifIXntsr4absl16HasAbslStringifyIT_EE5valueEiE4typeELi0EEERS2_RKS5_
>>> referenced by daemon.cpp
>>>               src/daemon/libdaemon.a(daemon.cpp.o):(absl::lts_20250127::log_internal::LogMessage::operator<<(unsigned long))
mold: error: undefined symbol: _ZN4absl12lts_2025012712log_internal10LogMessagelsIiTnNSt9enable_ifIXntsr4absl16HasAbslStringifyIT_EE5valueEiE4typeELi0EEERS2_RKS5_
>>> referenced by daemon.cpp
>>>               src/daemon/libdaemon.a(daemon.cpp.o):(absl::lts_20250127::log_internal::LogMessage::operator<<(int))
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sharder996** [comment]
I ran into this when porting to ppc64. I thought something changed in the ABI and one of the gcc compiled dependencies from vcpkg isn't compatible with clang compiled Multipass.
